name: Burp Suite DAST Scan

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  burp_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Burp Suite Scan (via API)
        run: |
          curl -X POST "https://your-burp-api-endpoint" -d '{"scanTarget": "http://your-app-url"}'

      - name: Fetch and store Burp report
        run: |
          curl -X GET "https://your-burp-api-endpoint/reports" -o burp_report.html

      - name: Commit and Push Burp Report
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Set up authentication with the GITHUB_TOKEN
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          git add burp_report.html
          git commit -m "Add Burp Suite scan report"
          git push
