name: OWASP ZAP DAST Scan

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OWASP ZAP
        run: |
          sudo apt-get update
          sudo apt-get install -y zaproxy

      - name: Set Target URL from Secrets
        run: echo "Running OWASP ZAP scan on $TARGET_URL"
        env:
          TARGET_URL: ${{ secrets.ZAP_TARGET_URL }}

      - name: Run OWASP ZAP DAST Scan
        run: |
          zap-cli quick-scan --self-contained --start-url ${{ secrets.ZAP_TARGET_URL }} --output-file zap-report.html

      - name: Upload OWASP ZAP Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html
