name: OWASP ZAP Scan with Installer

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Download and Install ZAP
        run: |
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.15.0/ZAP_2.15.0_unix.sh -O zap-installer.sh
          chmod +x zap-installer.sh
          ./zap-installer.sh -q -dir zap-install
          echo "$PWD/zap-install" >> $GITHUB_PATH

      - name: Run ZAP Baseline Scan
        run: |
          ./zap-install/zap.sh -cmd \
            -quickurl "${{ secrets.ZAP_TARGET_URL }}" \
            -quickout zap_report.html \
            -quickprogress \
            -silent

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-html-report
          path: zap_report.html
