name: Nikto DAST Scan

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  nikto_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Nikto
        run: |
          sudo apt-get update
          sudo apt-get install -y nikto

      - name: Run Nikto Scan
        run: |
          nikto -h http://your-app-url -o nikto-report.html

      - name: Upload Nikto Report
        run: |
          mkdir -p ${{ github.workspace }}/reports
          mv nikto-report.html ${{ github.workspace }}/reports/

      - name: Commit and Push Report
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add reports/
          git commit -m "Add Nikto scan report"
          git push
