name: OWASP ZAP Scan

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read # optional
      security-events: write # optional
      issues: none # 🚫 disable issue creation to avoid the error

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: ${{ secrets.ZAP_TARGET_URL }}
          cmd_options: "-a -T 5 -m 5"
          fail_action: false # don't fail even if issues found
          allow_issue_writing: false # 🚫 prevent GitHub issue creation

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: owasp-zap-report.html
