name: Nuclei DAST Scan

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  nuclei_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Nuclei
        run: |
          curl -s https://api.github.com/repos/projectdiscovery/nuclei/releases/latest \
            | grep "browser_download_url.*linux_amd64.zip" \
            | cut -d : -f 2,3 \
            | tr -d \" \
            | wget -qi -
          unzip -o nuclei_*_linux_amd64.zip
          sudo mv nuclei /usr/local/bin/
          nuclei --version

      - name: Set Target URL from Secrets
        run: echo "Running Nuclei scan on $TARGET_URL"
        env:
          TARGET_URL: ${{ secrets.ZAP_TARGET_URL }}

      - name: Run Nuclei Scan
        run: |
          mkdir -p reports
          nuclei -u ${{ secrets.ZAP_TARGET_URL }} -o reports/nuclei-report.txt

      - name: Upload Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-report
          path: reports/nuclei-report.txt
